### PR TITLE
Add tool to convert skyportal lightcurves to nmma format

### PR DESCRIPTION
**Pull request by bfhealy**
This PR adds a tool to convert light curves downloaded from the skyportal/fritz frontend to NMMA format. Also, the Injections & observational data documentation is updated with an example lightcurve downloaded from SkyPortal.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@bfhealy in show photometry table, I get mag and magerr. I opened a quick PR for the export button (https://github.com/skyportal/skyportal/pull/4708), although honestly I kind of wonder if we should remove this button and focus on the photometry table, which seems better. What do you think?

**Comment by bfhealy** [comment]
@mcoughlin Thanks for that PR - I also think the photometry table is the better place to be downloading lightcurves (I was testing only with the "Export Bold Light Curve to CSV" button).

**Comment by mcoughlin** [comment]
@bfhealy https://github.com/skyportal/skyportal/pull/4709

**Review by mcoughlin — APPROVED** [review]
LGTM!

**Comment by bfhealy** [comment]
@mcoughlin Any concern about the test failures? They look to be related to coveralls.

**Comment by mcoughlin** [comment]
@bfhealy not really. can usually rerun those tests.

**Pull request merged**
