### PR TITLE
Versioning change

### PR DESCRIPTION
**Pull request by Theodlz**
An attempt to address the versioning differently, similar to how https://github.com/joblib/joblib does it for example.

### CODE REVIEW

**Comment by sahiljhawar** [comment]
will the bumpver still work as usual? You can check using `bumpver update --patch --no-commit --no-tag-commit --no-push`

**Comment by Theodlz** [comment]
Hi @sahiljhawar, yes I gave it a go (a different cmd tho, not committing anything but just running it to output in the stdout) and it did update the versions in both pyproject.toml and __init__.py

**Comment by sahiljhawar** [comment]
okay, great!

@mcoughlin merge?

**Comment by mcoughlin** [comment]
Yes sir. Just edit the title not to have WIP. @sahiljhawar

**Comment by sahiljhawar** [comment]
@Theodlz any more changes to this?

**Comment by Theodlz** [comment]
@sahiljhawar I don't believe so no! We're keeping 0.1.3 here for now, right?

**Comment by sahiljhawar** [comment]
I think so.

**Pull request merged**
