### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by sahiljhawar**
Changed doc theme to accomodate warning boxes. Updated documentation for conda installation and mac

### CODE REVIEW

**Comment by mcoughlin** [comment]
@sahiljhawar can you please add me to your branch?

I needed to add:

linkify-it-py
myst-parser                                                                     
sphinx-book-theme

to doc_requirements to get it to build.

**Comment by sahiljhawar** [comment]
@mcoughlin I have sent you an invite from my (forked) repo, will that work?

**Comment by mcoughlin** [comment]
@sahiljhawar yes that's exactly what I meant.

**Review by mcoughlin — APPROVED** [review]
LGTM

**Pull request merged**
