### PR TITLE
Update python-package.yml

### PR DESCRIPTION
**Pull request by sahiljhawar**
Fixed syntax

### CODE REVIEW

**Review by mcoughlin — APPROVED** [review]
LGTM

**Comment by sahiljhawar** [comment]
@mcoughlin can you redo the merge? The tests (at coverage) fails

**Comment by mcoughlin** [comment]
@sahiljhawar we can just do a new PR right? It seems like the code at least ran which was progress.

**Comment by sahiljhawar** [comment]
@mcoughlin Okay. Still trying to figure out how this works

**Pull request merged**
