### PR TITLE
Lightcurve Injection Unit Test

### PR DESCRIPTION
**Pull request by tylerbarna**
Same work/intent as PR #103, now without the commit issues. Quoting from closed PR: 

started work on injections unit test to determine why early time lightcurve values might differ between light_curve_generation and calling the lightcurveModel functions directly. While not complete, I've encountered an issue with light_curv_generation where it ignores the label argument and saves the lightcurve as 0.dat.

Beyond this issue, the next step for this unit test would be to define a function to read back in the command line lightcurve as well as a function to compare the command line and function generated lightcurves.

This is a unit test intended to investigate Issue #106 further

### CODE REVIEW

**Comment by tylerbarna** [comment]
As mentioned before, there is an adjacent issue with nmma_create_injection where the simulation_id key is not included, which is required for light_curve_generation. The unit test currently has a workaround for this that manually adds the simulation_id key/value to the injection file.

There is also an issue with light_curve_generation where the label flag is ignored, and the file created is saved as the simulation_id value for the specific injection. This may be the intended behavior of light_curve_generation, though the label flag for light_curve_analysis uses it as a filename element in associated files (excluding the lightcurve.png plot, though this is a separate issue detailed in issue #53 )

**Comment by bfhealy** [comment]
@tylerbarna I added code to include `simulation_id` in injection files where that field has been missing. Might be a good idea to remove the current workaround in this PR's code after merging the latest `main` branch.

**Comment by bfhealy** [comment]
Hi @tylerbarna, I've merged the latest nmma updates and addressed the `0.dat` lightcurve issue (for now). Turns out the `--label` argument was not being used for the lightcurve filename. Instead, the `simulation_id` was being used (0 in our case). Not sure if I might be breaking something else by changing the naming convention in `create_lightcurves.py`.

I also fixed some linting errors that popped up when I made the commit. I'm now able to run `python nmma/tests/injections.py` without any errors, although I know there's more functionality to be added.

**Comment by tylerbarna** [comment]
> Hi @tylerbarna, I've merged the latest nmma updates and addressed the `0.dat` lightcurve issue (for now). Turns out the `--label` argument was not being used for the lightcurve filename. Instead, the `simulation_id` was being used (0 in our case). Not sure if I might be breaking something else by changing the naming convention in `create_lightcurves.py`.
> 
> I also fixed some linting errors that popped up when I made the commit. I'm now able to run `python nmma/tests/injections.py` without any errors, although I know there's more functionality to be added.

Awesome, I'll re-merge those changes and finish up the unit test. The label and simulation_id issues are the only workarounds I can think of for running this properly, but now that they're fixed, it should be possible to properly finish the unit test

**Comment by bfhealy** [comment]
Sounds good!

**Comment by tylerbarna** [comment]
@bfhealy latest commit adds everything needed for testing lightcurve models to my knowledge. see 9617a09 commit notes regarding potential changes

**Comment by tylerbarna** [comment]
oh, going by the unit test checks,  there's something wrong lol

**Comment by mcoughlin** [comment]
@tylerbarna I copied over your test and made some small edits and it passes (locally at least). Please re-open if after taking a look anything looks problematic and such.

**Pull request closed without merging**
