### PR TITLE
refactored systematics code

### PR DESCRIPTION
**Pull request by sahiljhawar**
Refactored systematics code to be more versatile. Now it is possible to use all analytical priors from bilby. Docs and tests will follow.

### CODE REVIEW

**Review by mcoughlin — COMMENTED** [review]
Why are all those tests now commented?

**Comment by sahiljhawar** [comment]
I have to change few of the tests, that's why commented all the tests for now.

**Review by mcoughlin — APPROVED** [review]
LGTM

**Review by tsunhopang — APPROVED** [review]
LGTM

**Pull request merged**
