### PR TITLE
Adding neural network inference to NMMA

### PR DESCRIPTION
**Pull request by malinadesai**
A new function has been added to /nmma/em/ananlysis.py called nnanalysis that can accept either a light curve or an injection file and will produce a corner plot displaying the inference results. Helper functions and model weights are added to nmma/mlmodel. Running this will require the following two commands to be added when creating the nmma environment: conda install pytorch torchvision -c pytorch 
pip install nflows

### CODE REVIEW

**Comment by tsunhopang** [comment]
@malinadesai could you update the requirement to include the new packages required?

**Comment by sahiljhawar** [comment]
@malinadesai can you also add a test for neuralnet. See here https://github.com/nuclear-multimessenger-astronomy/nmma/blob/a83be30800cb2ecaa172f494c7d54ee7ee726084/nmma/tests/analysis.py#L93

**Review by sahiljhawar — COMMENTED** [review]
We already have a documentation for injection. Can you add docs for the neuralnet, for example limited filters, only Ka2017 and a full neuralnet command. Can you also add the input files required, I can try adding the test.

**Comment by malinadesai** [comment]
@tsunhopang @sahiljhawar I added an ml_requirements.txt file that contains torch and nflows, and i was able to successfully create a new environment when running pip install -r ml_requirements.txt. I also added lfi_analysis.md to the doc directory with example use and addressing the limitations. I also added a new test function to nmma/tests/analysis.py called def test_nn_analysis(args). I'm not sure if that function is the appropriate way to add a test, so it could definitely benefit from a review.

**Comment by sahiljhawar** [comment]
hehe, thanks for the test

**Comment by sahiljhawar** [comment]
@mcoughlin @tsunhopang is there a need of refactoring since `nnanalysis` have a lot of similar code to `analysis`?

**Comment by mcoughlin** [comment]
@sahiljhawar @tsunhopang I suggest prioritizing getting this merged, and work on a refactor in a second PR.

**Comment by sahiljhawar** [comment]
@malinadesai can you have a look at the CI and the reason for `KeyError`?

**Comment by sahiljhawar** [comment]
Tests are passing, LGTM

**Comment by mcoughlin** [comment]
@sahiljhawar feel free to give an approving review and merge!

**Comment by sahiljhawar** [comment]
@malinadesai you should reset your `main` branch with NMMA `main` branch. As Michael once said, "Please use a branch for next time."

**Comment by sahiljhawar** [comment]
@malinadesai you should reset your main branch with NMMA main branch. As @mcoughlin once said, "Please use a branch for next time."

**Pull request merged**
