### PR TITLE
add filter check in ztf sampling

### PR DESCRIPTION
**Pull request by tylerbarna**
In injection.py, checks to see if current filter in loop of ztf-sampling is in the filter arguments. if not, continues to next filter without sampling. Retains requirement that filter is either g,r, or i for ztf. Shouldn't alter any other behaviour.

### CODE REVIEW

**Comment by tylerbarna** [comment]
To validate the functionality, should run something like 
`nmma_create_injection --injection-file example_files/sim_events/injections.dat --prior-file priors/Bu2019lm.prior --eos-file example_files/eos/ALF2.dat --binary-type BNS --n-injection 100 --original-parameters --extension json --aligned-spin
`
and then 
`    light_curve_analysis --model Bu2019lm --svd-path ./svdmodels --outdir outdir --label injection --prior priors/Bu2019lm.prior --tmin 0.1 --tmax 20 --dt 0.5 --error-budget 1 --nlive 512 --Ebv-max 0 --injection ./injection.json --injection-num 0 --injection-outfile outdir/lc.csv --generation-seed 42 --filters g --plot --remove-nondetections --ztf-uncertainties --ztf-sampling --ztf-ToO 180
`
using current version of nmma vs this PR. with current nmma version, lc.csv should ouput a lightcurve with g,r, and i despite argument. With new version, should output lightcurve with only g filter.

**Comment by tylerbarna** [comment]
I added a second conditional to the ztf sampling portion of injection.py; currently, there are two instances of "for filt, group in sim.groupby("passband"):", so an additional conditional checking if the filter is in the argument list is required.

**Comment by tylerbarna** [comment]
I would also recommend testing the functionality with the above code using a second model in addition to nugent-hyper, like Bu2019lm or TrPi2018

**Comment by mcoughlin** [comment]
@weizmannk can you take a look?

**Comment by weizmannk** [comment]
@mcoughlin  
I wait for @tylerbarna  confirmation.

To be more clear when we replace #bands = {1: "g", 2: "r", 3: "i"} by   bands = {i+1: b for i, b in enumerate(args.filters.split(","))}. 
there are always {1: "g", 2: "r", 3: "i"} in the code. 
This could generate errors in case one of the filters is not provided .

Forexample  here https://github.com/nuclear-multimessenger-astronomy/nmma/blob/b2586357f4a646e2bf0549ab4ae22fcaa7fe56e9/nmma/em/injection.py#L210

**Comment by tylerbarna** [comment]
@weizmannk 
I wasn't encountering that issue, at least in the ztf sampling portion; in each of the relevant loops, it checks to see if the filter from sim['passband'] is in the arguments list; if not, it moves to the next filter

**Comment by weizmannk** [comment]
@tylerbarna  ok good news, thanks

**Comment by tylerbarna** [comment]
does it cause an issue when you aren't using the ztf sampling?

**Review by weizmannk — APPROVED** [review]
LGTM

**Comment by weizmannk** [comment]
@tylerbarna  
If we give all ztf filters as input it should be ok.
So for now it's ok .

My question here was more about those who will give 1 or 2 ZTF filters instead   as arguments all 3 at the same time. 
Any way I will  do a test with the **--train-stats**  when I get free time , to confirm all thing is ok, then let you know. 

Thank you.

**Comment by tylerbarna** [comment]
it seems light_curve_generation still ignores the requested filters if you call ztf-uncertainties and photometry-augmentation-times even when calling both filters and photometry-augmentation-filters

**Pull request merged**
