### PR TITLE
Add local-model-only flag to joint analyses

### PR DESCRIPTION
**Pull request by bfhealy**
This PR adds a `local-model-only` flag to joint analyses to avoid downloading models from gitlab/zenodo.

(Several automated linting updates to the code as well)

### CODE REVIEW

**Comment by bfhealy** [comment]
@bking-astro Once merged, this should allow you to skip the model download process by adding `local-model-only=True` to the `## EM arguments` section of your `config.ini` file.

**Comment by sahiljhawar** [comment]
@bking-astro Can you test this locally and confirm if this works?

**Comment by bfhealy** [comment]
Update: the flag appears to be working as intended, but we're working through what may be a cluster-specific issue with mpi.

**Comment by sahiljhawar** [comment]
LGTM

**Review by sahiljhawar — APPROVED** [review]
LGTM

**Pull request merged**
