### PR TITLE
Better summary plot for lightcurve-analysis

### PR DESCRIPTION
**Pull request by tsunhopang**
Updating the best fit plots to be more informative.

Example plots can be found at https://enlil.gw.physik.uni-potsdam.de/~ppang/Bu2023Ye_uniform_lightcurves/

The best-fit plots are created per filter, and the chi2 per data point is plotted with the total chi2 shown in the title.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@tsunhopang these are looking better. Are we still going to have a single plot where all of these are shown in one panel, as you would want to show on a website or even a paper?

**Comment by tsunhopang** [comment]
@mcoughlin I am a bit indecisive about this. For publications, we always have to remake the plots for styling, etc. And for diagnosis, it is better to have a detailed look at each panel. However, I think having a summary HTML is a good middle ground. Lemme work on that.

**Comment by mcoughlin** [comment]
@Theodlz i am wondering what might work best for us, given desire for a display in SkyPortal. Could we handle multiple figures?

@tsunhopang We have benefited from the nice representation sncosmo has for the light curve fits, that single panel is very effective at showing fit quality in one look.

**Comment by tsunhopang** [comment]
@mcoughlin I see, lemme combine the plots then

**Comment by mcoughlin** [comment]
@tsunhopang did you end up combining the plots?

**Comment by mcoughlin** [comment]
@tsunhopang any luck?

**Comment by tsunhopang** [comment]
@mcoughlin , what do you think about this figure? If all good, I will clean up the code a bit and merge it

image

**Comment by mcoughlin** [comment]
@tsunhopang beautiful.

**Comment by tsunhopang** [comment]
@mcoughlin could you approve it?

**Review by mcoughlin — APPROVED** [review]
LGTM

**Pull request merged**
