### PR TITLE
pca_fit is added to the code

### PR DESCRIPTION
**Pull request by pouyansalehi**
Hi Michael
I think this one works.

### CODE REVIEW

**Review by mcoughlin — CHANGES_REQUESTED** [review]
@pouyansalehi There should be some kind of place where the default reduc_method is the old version for backwards compatibility. i.e. something like

reduc_method = svd_mag_model[filt].get('reduc_method', 'svd')

and then do the if statement with that.

**Comment by pouyansalehi** [comment]
is that satisfying?

**Review by mcoughlin — APPROVED** [review]
@weizmannk please check when you have time.

@pouyansalehi for this to be used, this flag will also need to be added into the training. Are you also planning on opening a PR on that side?

**Comment by pouyansalehi** [comment]
@mcoughlin: Yes, of course . But for now, I just wanted to prepare the code for Mouza do her PE runs ASAP.

**Comment by mcoughlin** [comment]
@weizmannk Ping.

**Pull request closed without merging**
