### PR TITLE
Create LC-simulatori.ipynb

### PR DESCRIPTION
**Pull request by FabioRagosta**
A tutorial notebook to show how to use the class objects in nmma to simulate lightcurves

### CODE REVIEW

**Review by mcoughlin — CHANGES_REQUESTED** [review]
@FabioRagosta Could you also add a note to the README pointing to the presence of your tutorial? Then it should be ready to go in.

**Comment by ritwiksharma049** [comment]
Is this added in README yet? I can add it if need be, if it's ready to go in.

**Review by FabioRagosta — COMMENTED** [review]
README updates

**Comment by mcoughlin** [comment]
@ritwiksharma049 @tylerbarna Could you please review this and approve if reasonable?

**Comment by tylerbarna** [comment]
> @ritwiksharma049 @tylerbarna Could you please review this and approve if reasonable?

will do

**Comment by tylerbarna** [comment]
It seems that there's a variable, 'training_data' that is not defined. Is that intentional?

**Comment by mcoughlin** [comment]
@FabioRagosta i am hoping that we can merge this. Can you check the variable?

**Comment by tylerbarna** [comment]
Updated Pull request at: https://github.com/nuclear-multimessenger-astronomy/nmma/pull/63

**Pull request closed without merging**
