### PR TITLE
Run workflow on pull requests

### PR DESCRIPTION
**Pull request by bfhealy**
This PR attempts to run the workflow in `python-package.yml` on pull requests. It also standardizes the syntax of `deploy-github-pages.yml` with the other workflow files.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@bfhealy Maybe should take advantage of this change and also try checking 3.10?

**Comment by bfhealy** [comment]
@mcoughlin That's a good idea!

**Comment by bfhealy** [comment]
@mcoughlin I also noticed that the branch in `build-deploy-contained.yml` is `master` instead of `main`:
```
name: CI to Docker Hub

on:
  push:
    branches: [ master ]
```

I think that's referring to this repo, so it should probably be updated if we want this workflow running.

**Comment by mcoughlin** [comment]
@bfhealy Can you update that in this PR too then?

**Review by mcoughlin — APPROVED** [review]
Thanks @bfhealy. LGTM.

**Pull request merged**
