### PR TITLE
Allow user specify ra,dec for fits input

### PR DESCRIPTION
**Pull request by tsunhopang**
@mcoughlin Adding the missed functionality of letting user specify ra and dec in the prior file when using fits input

MAP iota prior with the gw170817.fits:
image

iota prior with ra = 3.44616, and dec = -0.408084:
image

### CODE REVIEW

**Review by mcoughlin — APPROVED** [review]
LGTM

Maybe should note somewhere the radian bit? Or specify somehow?

**Comment by tsunhopang** [comment]
It is input via the prior file, from which the ra and dec are always assumed to be radian (the same as in bilby)

**Comment by mcoughlin** [comment]
Great thanks @tsunhopang

**Comment by tsunhopang** [comment]
@bfhealy could you check of the failing test for training?

**Comment by bfhealy** [comment]
@tsunhopang Sure, looks like it has something to do with this error:

```
TypeError: Could not locate function 'mse'. Make sure custom classes are decorated with `@keras.saving.register_keras_serializable()`. Full object config: {'module': 'keras.metrics', 'class_name': 'function', 'config': 'mse', 'registered_name': 'mse'}
```

I'll look into it some more, probably related to the recent tensorflow 2.16.1 release.

**Comment by bfhealy** [comment]
@tsunhopang I propose to merge #334 to avoid this error for now. #335 is a reminder to refactor the code the address this more thoroughly in the future.

**Pull request merged**
