### PR TITLE
add support for time dependent (and filter dependent) systematic error

### PR DESCRIPTION
**Pull request by sahiljhawar**
Copy of #253 

This PR adds support for sampled systematic error and time (and filter) dependent (interpolated) systematic error. For optimum performance it is recommended that the filters to be used for systematic biases should be less than or equal to the no of filters being used for the inference. If the no of filters for systematic biases is more than the no of `--filters` then the sampler will unnecessarily sample the priors which are of no use. For eg. if the filters in `--filters` is `sdssu,ps1__g,ps1__r,ps1__i,ps1__z,ps1__y,2massj,2massh,2massks` and you want to independently sample `ps1__r` and `ps1__i` filters then the yaml should be

```yaml
config:
  withTime:
    value: true
    filters: ["ps1__r", "ps1__i", null]
    ...
    ...
```
null will be a single array which will be used for all other filters excluding `ps1__r` and `ps1__i`.

The option is still there to add the systematic error in the prior file, however changed the name of the prior to be `sys_err`

### CODE REVIEW

**Comment by mcoughlin** [comment]
@sahiljhawar maybe you forgot a commit?

**Comment by sahiljhawar** [comment]
@mcoughlin which commit?

**Comment by mcoughlin** [comment]
@sahiljhawar i just notice the tests were failing due to a missing argument :)

**Comment by sahiljhawar** [comment]
yeah, I just checked the tests were failing due to `outdir` I guess. That's why the new commit with autodelete `outdir` after each test.

**Review by mcoughlin — APPROVED** [review]
This looks great. Can you add a page to the docs on this with maybe a few sample plots @sahiljhawar ?

**Comment by sahiljhawar** [comment]
Yeah sure, I can do that.

**Comment by mcoughlin** [comment]
@sahiljhawar any update herE?

**Comment by sahiljhawar** [comment]
@mcoughlin Waiting for @tsunhopang review

**Comment by tsunhopang** [comment]
Sorry for the delay, I should have time to look inti it this weekend.

**Comment by tsunhopang** [comment]
lgtm

**Pull request merged**
