### PR TITLE
Caching and test for GP

### PR DESCRIPTION
**Pull request by sahiljhawar**
This PR implements the use of caching to save the SVD models as cache and use them for all the future runs without the need to download models everytime. Fetching models from Zenodo is really slow, so for now the `svdmodel.tar` is hosted on Potsdam server. Following this, the analysis test has been updated to perform test on `Bu2019lm` since it makes use of the model. Also, note that if the tests are being used as is, do not use or create (from a code) any local folder by the name `svdmodels` as this can cause problems.

Note for admins: I would advise you to clear all the caches of this repo in order to have a fresh start.

### CODE REVIEW

**Review by mcoughlin — APPROVED** [review]
LGTM

**Comment by sahiljhawar** [comment]
Don't merge

**Comment by sahiljhawar** [comment]
Removed GRB model from injections.py test. Also, need to check the availability of caches from main branch to feature branch.

**Comment by sahiljhawar** [comment]
Cache present on the main branch cannot be accessed by the feature branches. This means, whenever PR comes, new caches are added to the repo alongside the cache of the main branch. Commit [5b374d4](https://github.com/nuclear-multimessenger-astronomy/nmma/pull/224/commits/5b374d4886b86e9f7e61f8efe665c0c80ccf1d33) adds a post PR merge cache deletion workflow.

**Comment by sahiljhawar** [comment]
@mcoughlin This can be merged now. Tests are passing. Cache workflow will be in action after the merge. In another PR I will pin parameters for GRB.

**Review by mcoughlin — APPROVED** [review]
LGTM!

**Pull request merged**
