### PR TITLE
Update analysis_slurm.py code for smoother analyses on Expanse

### PR DESCRIPTION
**Pull request by bfhealy**
This PR adjusts `analysis_slurm.py` to facilitate smoother analyses with Expanse:
- The structure of directories and files created by `analysis_slurm.py`  is modified, with the slurm script saved directly in the `nmma` directory.
-  More environment variables serve as wildcards for inputs specified by the user on SkyPortal (`TMIN`, `TMAX`, and `DT`). 
- The `--outdir` argument is adjusted to create a subdirectory labeled by each source's ID and analysis start time.
- A test is added to `tests/analysis.py` to test slurm script generation.

### CODE REVIEW

**Review by mcoughlin — APPROVED** [review]
LGTM

**Comment by mcoughlin** [comment]
@bfhealy feel free to merge once tests pass

**Comment by sahiljhawar** [comment]
`analysis_slurm.main()` is called without any arguments, even without slurm specific arguments!? Also I think `args` in `test_analysis` should be `global` so that `test_analysis` args’ can be accessed by `test_analysis_slurm()`.

**Comment by sahiljhawar** [comment]
@mcoughlin I don't know about rebasing and dont want to mess up. Can you please merge this?

**Pull request merged**
