### PR TITLE
Implement wide NN to approximate GP

### PR DESCRIPTION
**Pull request by bfhealy**
This PR modifies the NN used by tensorflow when running `create_svdmodel`. In an effort to approximate `sklearn_gp` performance, the NN is made wider and shallower.

### CODE REVIEW

**Comment by bfhealy** [comment]
@mcoughlin I think training and inference run decently well with the latest NN architecture in this PR. Is it ok (W.R.T. proprietary data) if I post some diagnostic plot outputs from `create_svdmodel` and `light_curve_analysis` using Bu2022Ye and the `lcs_bulla_2022` light curves?

**Comment by mcoughlin** [comment]
@bfhealy yup.

**Comment by bfhealy** [comment]
Since there is some strange behavior at early times, I also ran training with `tmin` set to 0.5:

injection_Bu2022Ye_lightcurves_2048_d0 6_t0 5

**Comment by bfhealy** [comment]
This is the corner plot resulting from running `light_curve_analysis` on an injection using the trained model:

injection_corner

**Comment by bfhealy** [comment]
And this is the (crowded) light curve output from running `light_curve_analysis`:

lightcurves

**Comment by mcoughlin** [comment]
@bfhealy I suggest we roll forward with this. You can send the models to @Theodlz to have them put on Zenodo.

Thanks for making this happen.

**Review by mcoughlin — APPROVED** [review]
LGTM!

**Pull request merged**
