### PR TITLE
add LANL models

### PR DESCRIPTION
**Pull request by mcoughlin**
This PR adds LANL models. Based on work by @bking-astro.

### CODE REVIEW

**Comment by mcoughlin** [comment]
@tylerbarna @weizmannk Can I get a review please?

**Comment by tylerbarna** [comment]
@mcoughlin do we have a LANL2022_mag.pkl file?

**Comment by tylerbarna** [comment]
getting a gps keyerror, will [investigate 
[LANL2022_error.txt](https://github.com/nuclear-multimessenger-astronomy/nmma/files/11125423/LANL2022_error.txt)

**Comment by tylerbarna** [comment]
light_curve_generation also isn't working, but that makes sense since there are _mag and _lbol pkl files 

`(pr_nmma) tyler@Desktop:~/nmma$ light_curve_generation --model LANL2022 --outdir outdir --label LANL_injection  --injection ./injection.json --filters g,r,i
WARNING: AstropyDeprecationWarning: The update_default_config function is deprecated and may be removed in a future version. [sncosmo]
Install afterglowpy if you want to timeout simulations.
Traceback (most recent call last):
  File "/home/tyler/anaconda3/envs/pr_nmma/bin/light_curve_generation", line 8, in <module>
    sys.exit(main())
  File "/home/tyler/anaconda3/envs/pr_nmma/lib/python3.8/site-packages/nmma/em/create_lightcurves.py", line 250, in main
    light_curve_model = SVDLightCurveModel(**light_curve_kwargs)
  File "/home/tyler/anaconda3/envs/pr_nmma/lib/python3.8/site-packages/nmma/em/model.py", line 193, in __init__
    with open(mag_modelfile, "rb") as handle:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tyler/anaconda3/envs/pr_nmma/lib/python3.8/site-packages/nmma/em/svdmodels/LANL2022_mag.pkl'`

**Comment by tylerbarna** [comment]
@weizmannk could you see if the error I encountered is replicated?

**Pull request merged**
