### PR TITLE
Expanse Jobscript and Quick Start Fix.

### PR DESCRIPTION
**Pull request by ritwiksharma049**
I have added the Expanse example bulk job script and explain the difference between SVD/Non-SVD on quick start page.

### CODE REVIEW

**Review by weizmannk — APPROVED** [review]
The nmma command lines are correct. 
Except that I have no experience on slrum.

**Comment by ritwiksharma049** [comment]
These changes don't reflect on the docs yet. Am I missing something?

**Comment by mcoughlin** [comment]
https://nuclear-multimessenger-astronomy.github.io/nmma/

What is missing?

**Comment by ritwiksharma049** [comment]
The cluster page.

**Comment by mcoughlin** [comment]
@ritwiksharma049 where did you add the link?

**Comment by ritwiksharma049** [comment]
I only added the document in the doc folder. Sorry about that. Where do I
link it?

**Comment by mcoughlin** [comment]
@ritwiksharma049 index.rst

User Guide
----------

.. toctree::
   :maxdepth: 1

   installation
   training
   fitting
   models
   GW-EM-resampling
   combined_analysis
   contributing

**Comment by ritwiksharma049** [comment]
Must be also why (
https://nuclear-multimessenger-astronomy.github.io/nmma/tutorials/) is
missing. I'll index them both. Thanks.

**Comment by ritwiksharma049** [comment]
This was Fabio's addition.

**Pull request merged**
