### PR TITLE
Update tutorial file and README

### PR DESCRIPTION
**Pull request by FabioRagosta**

### CODE REVIEW

**Comment by mcoughlin** [comment]
@ritwiksharma049 @tylerbarna please review.

**Review by tylerbarna — APPROVED** [review]
notebook functions as intended, made commit with minor tweaks/corrections in calling functions

**Comment by ritwiksharma049** [comment]
Is this ready to merge @tylerbarna?

**Comment by tylerbarna** [comment]
> Is this ready to merge @tylerbarna? 

I believe so, if you're running Mac os, might be good to give it a run to double check

**Comment by ritwiksharma049** [comment]
I do not have MacOS, I use a linux VM on windows for everything. What about that?

**Pull request merged**
